Repository cozy/cozy-flagship-app, pull requests merged in 2023-03, with the labels that each got.

#625 fix: update install home script
  scripts/install-home-registry.cmd.ts
Labels: bug

#581 doc: update codeowners
  CODEOWNERS
Labels: enhancement, actions

#702 fix: Android Universal Link
  android/app/src/main/AndroidManifest.xml
Labels: merge
